import { P2POrderInfo } from '@deriv/api-types';

export const mock_order: P2POrderInfo = {
    account_currency: 'USD',
    advert_details: {
        block_trade: 0,
        description: 'Mock order description',
        id: 'AD123456',
        payment_method: 'Bank transfer',
        type: 'buy',
    },
    advertiser_details: {
        first_name: 'John',
        id: 'CR1231125',
        is_online: 1,
        is_recommended: 1,
        last_name: 'Doe',
        last_online_time: 1678945678,
        loginid: 'john123',
        name: 'John Doe',
        completed_orders_count: 10,
        rating_average: 4.5,
        rating_count: 20,
        recommended_average: 4.5,
        recommended_count: 20,
        total_completion_rate: 0.5,
    },
    amount: 0.5,
    amount_display: '0.5',
    chat_channel_url: 'https://deriv.com/',
    client_details: {
        first_name: 'Jane',
        id: 'CR1231123',
        is_online: 0,
        last_name: 'Smith',
        last_online_time: 1678934567,
        loginid: 'jane456',
        name: 'Jane Smith',
    },
    contact_info: 'Contact information will be provided after order confirmation.',
    created_time: 1678923456,
    dispute_details: {
        dispute_reason: null,
        disputer_loginid: null,
    },
    expiry_time: 1678959319,
    id: 'ORD123456',
    is_incoming: 1,
    is_reviewable: 1,
    is_seen: 0,
    local_currency: 'EUR',
    payment_info: 'Payment details will be provided after order confirmation.',
    price: 55000,
    price_display: '55000',
    rate: 110000,
    rate_display: '110000',
    review_details: {
        created_time: 1678959319,
        rating: 5,
        recommended: 1,
    },
    status: 'pending',
    type: 'buy',
};
