import { TOrder } from 'Types';

export const mock_order: TOrder = {
    account_currency: 'USD',
    advert_details: {
        block_trade: false,
        description: 'Mock order description',
        id: 'AD123456',
        payment_method: 'Bank transfer',
        type: 'Buy',
    },
    advertiser_details: {
        first_name: 'John',
        id: 'CR1231125',
        is_online: true,
        is_recommended: true,
        last_name: 'Doe',
        last_online_time: 1678945678,
        loginid: 'john123',
        name: 'John Doe',
    },
    amount: 0.5,
    amount_display: '0.5',
    chat_channel_url: 'https://deriv.com/',
    client_details: {
        first_name: 'Jane',
        id: 'CR1231123',
        is_online: false,
        last_name: 'Smith',
        last_online_time: 1678934567,
        loginid: 'jane456',
        name: 'Jane Smith',
    },
    contact_info: 'Contact information will be provided after order confirmation.',
    created_time: 1678923456,
    dispute_details: {
        dispute_reason: null,
        disputer_loginid: null,
    },
    expiry_time: 1678959319,
    id: 'ORD123456',
    is_incoming: true,
    is_reviewable: true,
    is_seen: false,
    local_currency: 'EUR',
    payment_info: 'Payment details will be provided after order confirmation.',
    price: 55000,
    price_display: '55000',
    rate: 110000,
    rate_display: '110000',
    review_details: {
        comment: 'Mock review comment',
        rating: 5,
    },
    status: 'Pending',
    type: 'Buy',
};
